# Generated by Django 6.0.2 on 2026-09-17 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-идентификатор (slug)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(default='dumbbell', max_length=50, verbose_name='Иконка (Lucide)')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=32, unique=True, verbose_name='Номер заказа')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО покупателя')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
                ('city', models.CharField(default='Москва', max_length=100, verbose_name='Город')),
                ('address', models.TextField(verbose_name='Адрес доставки')),
                ('payment_method', models.CharField(choices=[('online', 'Банковской картой онлайн (СБП / МИР)'), ('courier', 'Оплата при получении курьеру'), ('crypto', 'USDT / Криптовалюта')], default='online', max_length=30, verbose_name='Способ оплаты')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий к заказу')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма заказа (₽)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Скидка (₽)')),
                ('status', models.CharField(choices=[('new', 'Новый заказ'), ('processing', 'В обработке'), ('shipped', 'Отправлен / В доставке'), ('completed', 'Выполнен'), ('cancelled', 'Отменён')], default='new', max_length=20, verbose_name='Статус заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название товара')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-идентификатор (slug)')),
                ('tagline', models.CharField(blank=True, max_length=255, verbose_name='Короткий слоган')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('full_description', models.TextField(verbose_name='Полное описание / О продукте')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (₽)')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена (₽)')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Изображение товара')),
                ('servings', models.CharField(blank=True, max_length=100, verbose_name='Количество порций')),
                ('weight_volume', models.CharField(blank=True, max_length=100, verbose_name='Вес / Объем')),
                ('flavor', models.CharField(blank=True, max_length=100, verbose_name='Вкус')),
                ('rating', models.FloatField(default=5.0, verbose_name='Рейтинг (от 1 до 5)')),
                ('reviews_count', models.PositiveIntegerField(default=24, verbose_name='Количество отзывов')),
                ('badge', models.CharField(blank=True, max_length=50, verbose_name='Бейдж (Хит, Скидка и т.д.)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Флагман на главной')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='Хит продаж')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('specs_json', models.JSONField(blank=True, default=dict, verbose_name='Характеристики / БЖУ (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-is_featured', '-is_bestseller', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за шт.')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='store.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Имя автора')),
                ('role_or_city', models.CharField(blank=True, default='PRO Атлет', max_length=100, verbose_name='Статус / Город')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Оценка (1-5)')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('avatar_text', models.CharField(default='AP', max_length=5, verbose_name='Инициалы')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Одобрен для показа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отзыва')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='store.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
    ]
